// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sentry

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDashboard(ctx *pulumi.Context, args *LookupDashboardArgs, opts ...pulumi.InvokeOption) (*LookupDashboardResult, error) {
	var rv LookupDashboardResult
	err := ctx.Invoke("sentry:index/getDashboard:getDashboard", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDashboard.
type LookupDashboardArgs struct {
	InternalId   string `pulumi:"internalId"`
	Organization string `pulumi:"organization"`
}

// A collection of values returned by getDashboard.
type LookupDashboardResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id           string               `pulumi:"id"`
	InternalId   string               `pulumi:"internalId"`
	Organization string               `pulumi:"organization"`
	Title        string               `pulumi:"title"`
	Widgets      []GetDashboardWidget `pulumi:"widgets"`
}

func LookupDashboardOutput(ctx *pulumi.Context, args LookupDashboardOutputArgs, opts ...pulumi.InvokeOption) LookupDashboardResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupDashboardResult, error) {
			args := v.(LookupDashboardArgs)
			r, err := LookupDashboard(ctx, &args, opts...)
			var s LookupDashboardResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupDashboardResultOutput)
}

// A collection of arguments for invoking getDashboard.
type LookupDashboardOutputArgs struct {
	InternalId   pulumi.StringInput `pulumi:"internalId"`
	Organization pulumi.StringInput `pulumi:"organization"`
}

func (LookupDashboardOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDashboardArgs)(nil)).Elem()
}

// A collection of values returned by getDashboard.
type LookupDashboardResultOutput struct{ *pulumi.OutputState }

func (LookupDashboardResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDashboardResult)(nil)).Elem()
}

func (o LookupDashboardResultOutput) ToLookupDashboardResultOutput() LookupDashboardResultOutput {
	return o
}

func (o LookupDashboardResultOutput) ToLookupDashboardResultOutputWithContext(ctx context.Context) LookupDashboardResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupDashboardResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) InternalId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.InternalId }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Organization }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDashboardResult) string { return v.Title }).(pulumi.StringOutput)
}

func (o LookupDashboardResultOutput) Widgets() GetDashboardWidgetArrayOutput {
	return o.ApplyT(func(v LookupDashboardResult) []GetDashboardWidget { return v.Widgets }).(GetDashboardWidgetArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDashboardResultOutput{})
}
