// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sentry

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupKey(ctx *pulumi.Context, args *LookupKeyArgs, opts ...pulumi.InvokeOption) (*LookupKeyResult, error) {
	var rv LookupKeyResult
	err := ctx.Invoke("sentry:index/getKey:getKey", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getKey.
type LookupKeyArgs struct {
	First        *bool   `pulumi:"first"`
	Name         *string `pulumi:"name"`
	Organization string  `pulumi:"organization"`
	Project      string  `pulumi:"project"`
}

// A collection of values returned by getKey.
type LookupKeyResult struct {
	DsnCsp    string `pulumi:"dsnCsp"`
	DsnPublic string `pulumi:"dsnPublic"`
	// Deprecated: DSN (Deprecated) for the key.
	DsnSecret string `pulumi:"dsnSecret"`
	First     *bool  `pulumi:"first"`
	// The provider-assigned unique ID for this managed resource.
	Id              string  `pulumi:"id"`
	IsActive        bool    `pulumi:"isActive"`
	Name            *string `pulumi:"name"`
	Organization    string  `pulumi:"organization"`
	Project         string  `pulumi:"project"`
	ProjectId       int     `pulumi:"projectId"`
	Public          string  `pulumi:"public"`
	RateLimitCount  int     `pulumi:"rateLimitCount"`
	RateLimitWindow int     `pulumi:"rateLimitWindow"`
	Secret          string  `pulumi:"secret"`
}

func LookupKeyOutput(ctx *pulumi.Context, args LookupKeyOutputArgs, opts ...pulumi.InvokeOption) LookupKeyResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupKeyResult, error) {
			args := v.(LookupKeyArgs)
			r, err := LookupKey(ctx, &args, opts...)
			var s LookupKeyResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupKeyResultOutput)
}

// A collection of arguments for invoking getKey.
type LookupKeyOutputArgs struct {
	First        pulumi.BoolPtrInput   `pulumi:"first"`
	Name         pulumi.StringPtrInput `pulumi:"name"`
	Organization pulumi.StringInput    `pulumi:"organization"`
	Project      pulumi.StringInput    `pulumi:"project"`
}

func (LookupKeyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKeyArgs)(nil)).Elem()
}

// A collection of values returned by getKey.
type LookupKeyResultOutput struct{ *pulumi.OutputState }

func (LookupKeyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKeyResult)(nil)).Elem()
}

func (o LookupKeyResultOutput) ToLookupKeyResultOutput() LookupKeyResultOutput {
	return o
}

func (o LookupKeyResultOutput) ToLookupKeyResultOutputWithContext(ctx context.Context) LookupKeyResultOutput {
	return o
}

func (o LookupKeyResultOutput) DsnCsp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeyResult) string { return v.DsnCsp }).(pulumi.StringOutput)
}

func (o LookupKeyResultOutput) DsnPublic() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeyResult) string { return v.DsnPublic }).(pulumi.StringOutput)
}

// Deprecated: DSN (Deprecated) for the key.
func (o LookupKeyResultOutput) DsnSecret() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeyResult) string { return v.DsnSecret }).(pulumi.StringOutput)
}

func (o LookupKeyResultOutput) First() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupKeyResult) *bool { return v.First }).(pulumi.BoolPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupKeyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupKeyResultOutput) IsActive() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupKeyResult) bool { return v.IsActive }).(pulumi.BoolOutput)
}

func (o LookupKeyResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupKeyResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o LookupKeyResultOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeyResult) string { return v.Organization }).(pulumi.StringOutput)
}

func (o LookupKeyResultOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeyResult) string { return v.Project }).(pulumi.StringOutput)
}

func (o LookupKeyResultOutput) ProjectId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKeyResult) int { return v.ProjectId }).(pulumi.IntOutput)
}

func (o LookupKeyResultOutput) Public() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeyResult) string { return v.Public }).(pulumi.StringOutput)
}

func (o LookupKeyResultOutput) RateLimitCount() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKeyResult) int { return v.RateLimitCount }).(pulumi.IntOutput)
}

func (o LookupKeyResultOutput) RateLimitWindow() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKeyResult) int { return v.RateLimitWindow }).(pulumi.IntOutput)
}

func (o LookupKeyResultOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeyResult) string { return v.Secret }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupKeyResultOutput{})
}
