// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sentry

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "sentry:index/dashboard:Dashboard":
		r = &Dashboard{}
	case "sentry:index/issueAlert:IssueAlert":
		r = &IssueAlert{}
	case "sentry:index/key:Key":
		r = &Key{}
	case "sentry:index/metricAlert:MetricAlert":
		r = &MetricAlert{}
	case "sentry:index/organization:Organization":
		r = &Organization{}
	case "sentry:index/plugin:Plugin":
		r = &Plugin{}
	case "sentry:index/project:Project":
		r = &Project{}
	case "sentry:index/rule:Rule":
		r = &Rule{}
	case "sentry:index/team:Team":
		r = &Team{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:sentry" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, _ := PkgVersion()
	pulumi.RegisterResourceModule(
		"sentry",
		"index/dashboard",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"sentry",
		"index/issueAlert",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"sentry",
		"index/key",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"sentry",
		"index/metricAlert",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"sentry",
		"index/organization",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"sentry",
		"index/plugin",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"sentry",
		"index/project",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"sentry",
		"index/rule",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"sentry",
		"index/team",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"sentry",
		&pkg{version},
	)
}
