// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sentry
{
    public static class GetDashboard
    {
        public static Task<GetDashboardResult> InvokeAsync(GetDashboardArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDashboardResult>("sentry:index/getDashboard:getDashboard", args ?? new GetDashboardArgs(), options.WithDefaults());

        public static Output<GetDashboardResult> Invoke(GetDashboardInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDashboardResult>("sentry:index/getDashboard:getDashboard", args ?? new GetDashboardInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDashboardArgs : global::Pulumi.InvokeArgs
    {
        [Input("internalId", required: true)]
        public string InternalId { get; set; } = null!;

        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        public GetDashboardArgs()
        {
        }
        public static new GetDashboardArgs Empty => new GetDashboardArgs();
    }

    public sealed class GetDashboardInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("internalId", required: true)]
        public Input<string> InternalId { get; set; } = null!;

        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        public GetDashboardInvokeArgs()
        {
        }
        public static new GetDashboardInvokeArgs Empty => new GetDashboardInvokeArgs();
    }


    [OutputType]
    public sealed class GetDashboardResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string InternalId;
        public readonly string Organization;
        public readonly string Title;
        public readonly ImmutableArray<Outputs.GetDashboardWidgetResult> Widgets;

        [OutputConstructor]
        private GetDashboardResult(
            string id,

            string internalId,

            string organization,

            string title,

            ImmutableArray<Outputs.GetDashboardWidgetResult> widgets)
        {
            Id = id;
            InternalId = internalId;
            Organization = organization;
            Title = title;
            Widgets = widgets;
        }
    }
}
