// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sentry
{
    public static class GetKey
    {
        public static Task<GetKeyResult> InvokeAsync(GetKeyArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetKeyResult>("sentry:index/getKey:getKey", args ?? new GetKeyArgs(), options.WithDefaults());

        public static Output<GetKeyResult> Invoke(GetKeyInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetKeyResult>("sentry:index/getKey:getKey", args ?? new GetKeyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetKeyArgs : global::Pulumi.InvokeArgs
    {
        [Input("first")]
        public bool? First { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        [Input("project", required: true)]
        public string Project { get; set; } = null!;

        public GetKeyArgs()
        {
        }
        public static new GetKeyArgs Empty => new GetKeyArgs();
    }

    public sealed class GetKeyInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("first")]
        public Input<bool>? First { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        public GetKeyInvokeArgs()
        {
        }
        public static new GetKeyInvokeArgs Empty => new GetKeyInvokeArgs();
    }


    [OutputType]
    public sealed class GetKeyResult
    {
        public readonly string DsnCsp;
        public readonly string DsnPublic;
        public readonly string DsnSecret;
        public readonly bool? First;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsActive;
        public readonly string? Name;
        public readonly string Organization;
        public readonly string Project;
        public readonly int ProjectId;
        public readonly string Public;
        public readonly int RateLimitCount;
        public readonly int RateLimitWindow;
        public readonly string Secret;

        [OutputConstructor]
        private GetKeyResult(
            string dsnCsp,

            string dsnPublic,

            string dsnSecret,

            bool? first,

            string id,

            bool isActive,

            string? name,

            string organization,

            string project,

            int projectId,

            string @public,

            int rateLimitCount,

            int rateLimitWindow,

            string secret)
        {
            DsnCsp = dsnCsp;
            DsnPublic = dsnPublic;
            DsnSecret = dsnSecret;
            First = first;
            Id = id;
            IsActive = isActive;
            Name = name;
            Organization = organization;
            Project = project;
            ProjectId = projectId;
            Public = @public;
            RateLimitCount = rateLimitCount;
            RateLimitWindow = rateLimitWindow;
            Secret = secret;
        }
    }
}
