// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sentry
{
    public static class GetTeam
    {
        public static Task<GetTeamResult> InvokeAsync(GetTeamArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTeamResult>("sentry:index/getTeam:getTeam", args ?? new GetTeamArgs(), options.WithDefaults());

        public static Output<GetTeamResult> Invoke(GetTeamInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTeamResult>("sentry:index/getTeam:getTeam", args ?? new GetTeamInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTeamArgs : global::Pulumi.InvokeArgs
    {
        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        [Input("slug", required: true)]
        public string Slug { get; set; } = null!;

        public GetTeamArgs()
        {
        }
        public static new GetTeamArgs Empty => new GetTeamArgs();
    }

    public sealed class GetTeamInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        [Input("slug", required: true)]
        public Input<string> Slug { get; set; } = null!;

        public GetTeamInvokeArgs()
        {
        }
        public static new GetTeamInvokeArgs Empty => new GetTeamInvokeArgs();
    }


    [OutputType]
    public sealed class GetTeamResult
    {
        public readonly bool HasAccess;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string InternalId;
        public readonly bool IsMember;
        public readonly bool IsPending;
        public readonly string Name;
        public readonly string Organization;
        public readonly string Slug;

        [OutputConstructor]
        private GetTeamResult(
            bool hasAccess,

            string id,

            string internalId,

            bool isMember,

            bool isPending,

            string name,

            string organization,

            string slug)
        {
            HasAccess = hasAccess;
            Id = id;
            InternalId = internalId;
            IsMember = isMember;
            IsPending = isPending;
            Name = name;
            Organization = organization;
            Slug = slug;
        }
    }
}
