// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sentry.Outputs
{

    [OutputType]
    public sealed class GetDashboardWidgetResult
    {
        public readonly string DisplayType;
        public readonly string Id;
        public readonly string Interval;
        public readonly ImmutableArray<Outputs.GetDashboardWidgetLayoutResult> Layouts;
        public readonly int Limit;
        public readonly ImmutableArray<Outputs.GetDashboardWidgetQueryResult> Queries;
        public readonly string Title;
        public readonly string WidgetType;

        [OutputConstructor]
        private GetDashboardWidgetResult(
            string displayType,

            string id,

            string interval,

            ImmutableArray<Outputs.GetDashboardWidgetLayoutResult> layouts,

            int limit,

            ImmutableArray<Outputs.GetDashboardWidgetQueryResult> queries,

            string title,

            string widgetType)
        {
            DisplayType = displayType;
            Id = id;
            Interval = interval;
            Layouts = layouts;
            Limit = limit;
            Queries = queries;
            Title = title;
            WidgetType = widgetType;
        }
    }
}
