// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// The target Sentry Base API URL in the format `https://[hostname]/api/`. The default value is `https://sentry.io/api/`.
// The value must be provided when working with Sentry On-Premise. The value can be sourced from the `SENTRY_BASE_URL`
// environment variable.
func GetBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "sentry:baseUrl")
}

// The authentication token used to connect to Sentry. The value can be sourced from the `SENTRY_AUTH_TOKEN` environment
// variable.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "sentry:token")
}
