# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .dashboard import *
from .get_dashboard import *
from .get_issue_alert import *
from .get_key import *
from .get_metric_alert import *
from .get_organization import *
from .get_team import *
from .issue_alert import *
from .key import *
from .metric_alert import *
from .organization import *
from .plugin import *
from .project import *
from .provider import *
from .rule import *
from .team import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_sentry.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_sentry.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "sentry",
  "mod": "index/dashboard",
  "fqn": "pulumi_sentry",
  "classes": {
   "sentry:index/dashboard:Dashboard": "Dashboard"
  }
 },
 {
  "pkg": "sentry",
  "mod": "index/issueAlert",
  "fqn": "pulumi_sentry",
  "classes": {
   "sentry:index/issueAlert:IssueAlert": "IssueAlert"
  }
 },
 {
  "pkg": "sentry",
  "mod": "index/key",
  "fqn": "pulumi_sentry",
  "classes": {
   "sentry:index/key:Key": "Key"
  }
 },
 {
  "pkg": "sentry",
  "mod": "index/metricAlert",
  "fqn": "pulumi_sentry",
  "classes": {
   "sentry:index/metricAlert:MetricAlert": "MetricAlert"
  }
 },
 {
  "pkg": "sentry",
  "mod": "index/organization",
  "fqn": "pulumi_sentry",
  "classes": {
   "sentry:index/organization:Organization": "Organization"
  }
 },
 {
  "pkg": "sentry",
  "mod": "index/plugin",
  "fqn": "pulumi_sentry",
  "classes": {
   "sentry:index/plugin:Plugin": "Plugin"
  }
 },
 {
  "pkg": "sentry",
  "mod": "index/project",
  "fqn": "pulumi_sentry",
  "classes": {
   "sentry:index/project:Project": "Project"
  }
 },
 {
  "pkg": "sentry",
  "mod": "index/rule",
  "fqn": "pulumi_sentry",
  "classes": {
   "sentry:index/rule:Rule": "Rule"
  }
 },
 {
  "pkg": "sentry",
  "mod": "index/team",
  "fqn": "pulumi_sentry",
  "classes": {
   "sentry:index/team:Team": "Team"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "sentry",
  "token": "pulumi:providers:sentry",
  "fqn": "pulumi_sentry",
  "class": "Provider"
 }
]
"""
)
