# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetIssueAlertResult',
    'AwaitableGetIssueAlertResult',
    'get_issue_alert',
    'get_issue_alert_output',
]

@pulumi.output_type
class GetIssueAlertResult:
    """
    A collection of values returned by getIssueAlert.
    """
    def __init__(__self__, action_match=None, actions=None, conditions=None, environment=None, filter_match=None, filters=None, frequency=None, id=None, internal_id=None, name=None, organization=None, project=None):
        if action_match and not isinstance(action_match, str):
            raise TypeError("Expected argument 'action_match' to be a str")
        pulumi.set(__self__, "action_match", action_match)
        if actions and not isinstance(actions, list):
            raise TypeError("Expected argument 'actions' to be a list")
        pulumi.set(__self__, "actions", actions)
        if conditions and not isinstance(conditions, list):
            raise TypeError("Expected argument 'conditions' to be a list")
        pulumi.set(__self__, "conditions", conditions)
        if environment and not isinstance(environment, str):
            raise TypeError("Expected argument 'environment' to be a str")
        pulumi.set(__self__, "environment", environment)
        if filter_match and not isinstance(filter_match, str):
            raise TypeError("Expected argument 'filter_match' to be a str")
        pulumi.set(__self__, "filter_match", filter_match)
        if filters and not isinstance(filters, list):
            raise TypeError("Expected argument 'filters' to be a list")
        pulumi.set(__self__, "filters", filters)
        if frequency and not isinstance(frequency, int):
            raise TypeError("Expected argument 'frequency' to be a int")
        pulumi.set(__self__, "frequency", frequency)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if internal_id and not isinstance(internal_id, str):
            raise TypeError("Expected argument 'internal_id' to be a str")
        pulumi.set(__self__, "internal_id", internal_id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if organization and not isinstance(organization, str):
            raise TypeError("Expected argument 'organization' to be a str")
        pulumi.set(__self__, "organization", organization)
        if project and not isinstance(project, str):
            raise TypeError("Expected argument 'project' to be a str")
        pulumi.set(__self__, "project", project)

    @property
    @pulumi.getter(name="actionMatch")
    def action_match(self) -> str:
        return pulumi.get(self, "action_match")

    @property
    @pulumi.getter
    def actions(self) -> Sequence[Mapping[str, Any]]:
        return pulumi.get(self, "actions")

    @property
    @pulumi.getter
    def conditions(self) -> Sequence[Mapping[str, Any]]:
        return pulumi.get(self, "conditions")

    @property
    @pulumi.getter
    def environment(self) -> str:
        return pulumi.get(self, "environment")

    @property
    @pulumi.getter(name="filterMatch")
    def filter_match(self) -> str:
        return pulumi.get(self, "filter_match")

    @property
    @pulumi.getter
    def filters(self) -> Sequence[Mapping[str, Any]]:
        return pulumi.get(self, "filters")

    @property
    @pulumi.getter
    def frequency(self) -> int:
        return pulumi.get(self, "frequency")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="internalId")
    def internal_id(self) -> str:
        return pulumi.get(self, "internal_id")

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def organization(self) -> str:
        return pulumi.get(self, "organization")

    @property
    @pulumi.getter
    def project(self) -> str:
        return pulumi.get(self, "project")


class AwaitableGetIssueAlertResult(GetIssueAlertResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIssueAlertResult(
            action_match=self.action_match,
            actions=self.actions,
            conditions=self.conditions,
            environment=self.environment,
            filter_match=self.filter_match,
            filters=self.filters,
            frequency=self.frequency,
            id=self.id,
            internal_id=self.internal_id,
            name=self.name,
            organization=self.organization,
            project=self.project)


def get_issue_alert(internal_id: Optional[str] = None,
                    organization: Optional[str] = None,
                    project: Optional[str] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetIssueAlertResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['internalId'] = internal_id
    __args__['organization'] = organization
    __args__['project'] = project
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('sentry:index/getIssueAlert:getIssueAlert', __args__, opts=opts, typ=GetIssueAlertResult).value

    return AwaitableGetIssueAlertResult(
        action_match=__ret__.action_match,
        actions=__ret__.actions,
        conditions=__ret__.conditions,
        environment=__ret__.environment,
        filter_match=__ret__.filter_match,
        filters=__ret__.filters,
        frequency=__ret__.frequency,
        id=__ret__.id,
        internal_id=__ret__.internal_id,
        name=__ret__.name,
        organization=__ret__.organization,
        project=__ret__.project)


@_utilities.lift_output_func(get_issue_alert)
def get_issue_alert_output(internal_id: Optional[pulumi.Input[str]] = None,
                           organization: Optional[pulumi.Input[str]] = None,
                           project: Optional[pulumi.Input[str]] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetIssueAlertResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
