# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetKeyResult',
    'AwaitableGetKeyResult',
    'get_key',
    'get_key_output',
]

@pulumi.output_type
class GetKeyResult:
    """
    A collection of values returned by getKey.
    """
    def __init__(__self__, dsn_csp=None, dsn_public=None, dsn_secret=None, first=None, id=None, is_active=None, name=None, organization=None, project=None, project_id=None, public=None, rate_limit_count=None, rate_limit_window=None, secret=None):
        if dsn_csp and not isinstance(dsn_csp, str):
            raise TypeError("Expected argument 'dsn_csp' to be a str")
        pulumi.set(__self__, "dsn_csp", dsn_csp)
        if dsn_public and not isinstance(dsn_public, str):
            raise TypeError("Expected argument 'dsn_public' to be a str")
        pulumi.set(__self__, "dsn_public", dsn_public)
        if dsn_secret and not isinstance(dsn_secret, str):
            raise TypeError("Expected argument 'dsn_secret' to be a str")
        if dsn_secret is not None:
            warnings.warn("""DSN (Deprecated) for the key.""", DeprecationWarning)
            pulumi.log.warn("""dsn_secret is deprecated: DSN (Deprecated) for the key.""")

        pulumi.set(__self__, "dsn_secret", dsn_secret)
        if first and not isinstance(first, bool):
            raise TypeError("Expected argument 'first' to be a bool")
        pulumi.set(__self__, "first", first)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if is_active and not isinstance(is_active, bool):
            raise TypeError("Expected argument 'is_active' to be a bool")
        pulumi.set(__self__, "is_active", is_active)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if organization and not isinstance(organization, str):
            raise TypeError("Expected argument 'organization' to be a str")
        pulumi.set(__self__, "organization", organization)
        if project and not isinstance(project, str):
            raise TypeError("Expected argument 'project' to be a str")
        pulumi.set(__self__, "project", project)
        if project_id and not isinstance(project_id, int):
            raise TypeError("Expected argument 'project_id' to be a int")
        pulumi.set(__self__, "project_id", project_id)
        if public and not isinstance(public, str):
            raise TypeError("Expected argument 'public' to be a str")
        pulumi.set(__self__, "public", public)
        if rate_limit_count and not isinstance(rate_limit_count, int):
            raise TypeError("Expected argument 'rate_limit_count' to be a int")
        pulumi.set(__self__, "rate_limit_count", rate_limit_count)
        if rate_limit_window and not isinstance(rate_limit_window, int):
            raise TypeError("Expected argument 'rate_limit_window' to be a int")
        pulumi.set(__self__, "rate_limit_window", rate_limit_window)
        if secret and not isinstance(secret, str):
            raise TypeError("Expected argument 'secret' to be a str")
        pulumi.set(__self__, "secret", secret)

    @property
    @pulumi.getter(name="dsnCsp")
    def dsn_csp(self) -> str:
        return pulumi.get(self, "dsn_csp")

    @property
    @pulumi.getter(name="dsnPublic")
    def dsn_public(self) -> str:
        return pulumi.get(self, "dsn_public")

    @property
    @pulumi.getter(name="dsnSecret")
    def dsn_secret(self) -> str:
        return pulumi.get(self, "dsn_secret")

    @property
    @pulumi.getter
    def first(self) -> Optional[bool]:
        return pulumi.get(self, "first")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> bool:
        return pulumi.get(self, "is_active")

    @property
    @pulumi.getter
    def name(self) -> Optional[str]:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def organization(self) -> str:
        return pulumi.get(self, "organization")

    @property
    @pulumi.getter
    def project(self) -> str:
        return pulumi.get(self, "project")

    @property
    @pulumi.getter(name="projectId")
    def project_id(self) -> int:
        return pulumi.get(self, "project_id")

    @property
    @pulumi.getter
    def public(self) -> str:
        return pulumi.get(self, "public")

    @property
    @pulumi.getter(name="rateLimitCount")
    def rate_limit_count(self) -> int:
        return pulumi.get(self, "rate_limit_count")

    @property
    @pulumi.getter(name="rateLimitWindow")
    def rate_limit_window(self) -> int:
        return pulumi.get(self, "rate_limit_window")

    @property
    @pulumi.getter
    def secret(self) -> str:
        return pulumi.get(self, "secret")


class AwaitableGetKeyResult(GetKeyResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetKeyResult(
            dsn_csp=self.dsn_csp,
            dsn_public=self.dsn_public,
            dsn_secret=self.dsn_secret,
            first=self.first,
            id=self.id,
            is_active=self.is_active,
            name=self.name,
            organization=self.organization,
            project=self.project,
            project_id=self.project_id,
            public=self.public,
            rate_limit_count=self.rate_limit_count,
            rate_limit_window=self.rate_limit_window,
            secret=self.secret)


def get_key(first: Optional[bool] = None,
            name: Optional[str] = None,
            organization: Optional[str] = None,
            project: Optional[str] = None,
            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetKeyResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['first'] = first
    __args__['name'] = name
    __args__['organization'] = organization
    __args__['project'] = project
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('sentry:index/getKey:getKey', __args__, opts=opts, typ=GetKeyResult).value

    return AwaitableGetKeyResult(
        dsn_csp=__ret__.dsn_csp,
        dsn_public=__ret__.dsn_public,
        dsn_secret=__ret__.dsn_secret,
        first=__ret__.first,
        id=__ret__.id,
        is_active=__ret__.is_active,
        name=__ret__.name,
        organization=__ret__.organization,
        project=__ret__.project,
        project_id=__ret__.project_id,
        public=__ret__.public,
        rate_limit_count=__ret__.rate_limit_count,
        rate_limit_window=__ret__.rate_limit_window,
        secret=__ret__.secret)


@_utilities.lift_output_func(get_key)
def get_key_output(first: Optional[pulumi.Input[Optional[bool]]] = None,
                   name: Optional[pulumi.Input[Optional[str]]] = None,
                   organization: Optional[pulumi.Input[str]] = None,
                   project: Optional[pulumi.Input[str]] = None,
                   opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetKeyResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
