// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DashboardWidget {
    displayType: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    interval?: pulumi.Input<string>;
    layout: pulumi.Input<inputs.DashboardWidgetLayout>;
    limit?: pulumi.Input<number>;
    queries: pulumi.Input<pulumi.Input<inputs.DashboardWidgetQuery>[]>;
    title: pulumi.Input<string>;
    widgetType?: pulumi.Input<string>;
}

export interface DashboardWidgetLayout {
    h: pulumi.Input<number>;
    minH: pulumi.Input<number>;
    w: pulumi.Input<number>;
    x: pulumi.Input<number>;
    y: pulumi.Input<number>;
}

export interface DashboardWidgetQuery {
    aggregates?: pulumi.Input<pulumi.Input<string>[]>;
    columns?: pulumi.Input<pulumi.Input<string>[]>;
    conditions?: pulumi.Input<string>;
    fieldAliases?: pulumi.Input<pulumi.Input<string>[]>;
    fields?: pulumi.Input<pulumi.Input<string>[]>;
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    orderBy?: pulumi.Input<string>;
}

export interface MetricAlertTrigger {
    actions?: pulumi.Input<pulumi.Input<inputs.MetricAlertTriggerAction>[]>;
    alertThreshold: pulumi.Input<number>;
    id?: pulumi.Input<string>;
    label: pulumi.Input<string>;
    resolveThreshold?: pulumi.Input<number>;
    thresholdType: pulumi.Input<number>;
}

export interface MetricAlertTriggerAction {
    id?: pulumi.Input<string>;
    targetIdentifier: pulumi.Input<string>;
    targetType: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

