// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DashboardWidget {
    displayType: string;
    id: string;
    interval: string;
    layout: outputs.DashboardWidgetLayout;
    limit: number;
    queries: outputs.DashboardWidgetQuery[];
    title: string;
    widgetType: string;
}

export interface DashboardWidgetLayout {
    h: number;
    minH: number;
    w: number;
    x: number;
    y: number;
}

export interface DashboardWidgetQuery {
    aggregates: string[];
    columns: string[];
    conditions: string;
    fieldAliases: string[];
    fields: string[];
    id: string;
    name?: string;
    orderBy: string;
}

export interface GetDashboardWidget {
    displayType: string;
    id: string;
    interval: string;
    layouts: outputs.GetDashboardWidgetLayout[];
    limit: number;
    queries: outputs.GetDashboardWidgetQuery[];
    title: string;
    widgetType: string;
}

export interface GetDashboardWidgetLayout {
    h: number;
    minH: number;
    w: number;
    x: number;
    y: number;
}

export interface GetDashboardWidgetQuery {
    aggregates: string[];
    columns: string[];
    conditions: string;
    fieldAliases: string[];
    fields: string[];
    id: string;
    name: string;
    orderBy: string;
}

export interface GetMetricAlertTrigger {
    actions: outputs.GetMetricAlertTriggerAction[];
    alertThreshold: number;
    id: string;
    label: string;
    resolveThreshold: number;
    thresholdType: number;
}

export interface GetMetricAlertTriggerAction {
    id: string;
    targetIdentifier: string;
    targetType: string;
    type: string;
}

export interface MetricAlertTrigger {
    actions?: outputs.MetricAlertTriggerAction[];
    alertThreshold: number;
    id: string;
    label: string;
    resolveThreshold: number;
    thresholdType: number;
}

export interface MetricAlertTriggerAction {
    id: string;
    targetIdentifier: string;
    targetType: string;
    type: string;
}
