// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sentry.Inputs
{

    public sealed class MetricAlertTriggerActionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("targetIdentifier", required: true)]
        public Input<string> TargetIdentifier { get; set; } = null!;

        [Input("targetType", required: true)]
        public Input<string> TargetType { get; set; } = null!;

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public MetricAlertTriggerActionGetArgs()
        {
        }
        public static new MetricAlertTriggerActionGetArgs Empty => new MetricAlertTriggerActionGetArgs();
    }
}
