// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sentry.Inputs
{

    public sealed class MetricAlertTriggerArgs : global::Pulumi.ResourceArgs
    {
        [Input("actions")]
        private InputList<Inputs.MetricAlertTriggerActionArgs>? _actions;
        public InputList<Inputs.MetricAlertTriggerActionArgs> Actions
        {
            get => _actions ?? (_actions = new InputList<Inputs.MetricAlertTriggerActionArgs>());
            set => _actions = value;
        }

        [Input("alertThreshold", required: true)]
        public Input<double> AlertThreshold { get; set; } = null!;

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("label", required: true)]
        public Input<string> Label { get; set; } = null!;

        [Input("resolveThreshold")]
        public Input<double>? ResolveThreshold { get; set; }

        [Input("thresholdType", required: true)]
        public Input<int> ThresholdType { get; set; } = null!;

        public MetricAlertTriggerArgs()
        {
        }
        public static new MetricAlertTriggerArgs Empty => new MetricAlertTriggerArgs();
    }
}
