// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getKey(args: GetKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetKeyResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("sentry:index/getKey:getKey", {
        "first": args.first,
        "name": args.name,
        "organization": args.organization,
        "project": args.project,
    }, opts);
}

/**
 * A collection of arguments for invoking getKey.
 */
export interface GetKeyArgs {
    first?: boolean;
    name?: string;
    organization: string;
    project: string;
}

/**
 * A collection of values returned by getKey.
 */
export interface GetKeyResult {
    readonly dsnCsp: string;
    readonly dsnPublic: string;
    /**
     * @deprecated DSN (Deprecated) for the key.
     */
    readonly dsnSecret: string;
    readonly first?: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly isActive: boolean;
    readonly name?: string;
    readonly organization: string;
    readonly project: string;
    readonly projectId: number;
    readonly public: string;
    readonly rateLimitCount: number;
    readonly rateLimitWindow: number;
    readonly secret: string;
}

export function getKeyOutput(args: GetKeyOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetKeyResult> {
    return pulumi.output(args).apply(a => getKey(a, opts))
}

/**
 * A collection of arguments for invoking getKey.
 */
export interface GetKeyOutputArgs {
    first?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    organization: pulumi.Input<string>;
    project: pulumi.Input<string>;
}
