// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Key extends pulumi.CustomResource {
    /**
     * Get an existing Key resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: KeyState, opts?: pulumi.CustomResourceOptions): Key {
        return new Key(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sentry:index/key:Key';

    /**
     * Returns true if the given object is an instance of Key.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Key {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Key.__pulumiType;
    }

    /**
     * DSN for the Content Security Policy (CSP) for the key.
     */
    public /*out*/ readonly dsnCsp!: pulumi.Output<string>;
    /**
     * DSN for the key.
     */
    public /*out*/ readonly dsnPublic!: pulumi.Output<string>;
    /**
     * @deprecated DSN (Deprecated) for the key.
     */
    public /*out*/ readonly dsnSecret!: pulumi.Output<string>;
    /**
     * Flag indicating the key is active.
     */
    public /*out*/ readonly isActive!: pulumi.Output<boolean>;
    /**
     * The name of the key.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The slug of the organization the key should be created for.
     */
    public readonly organization!: pulumi.Output<string>;
    /**
     * The slug of the project the key should be created for.
     */
    public readonly project!: pulumi.Output<string>;
    /**
     * The ID of the project that the key belongs to.
     */
    public /*out*/ readonly projectId!: pulumi.Output<number>;
    /**
     * Public key portion of the client key.
     */
    public /*out*/ readonly public!: pulumi.Output<string>;
    /**
     * Number of events that can be reported within the rate limit window.
     */
    public readonly rateLimitCount!: pulumi.Output<number>;
    /**
     * Length of time that will be considered when checking the rate limit.
     */
    public readonly rateLimitWindow!: pulumi.Output<number>;
    /**
     * Secret key portion of the client key.
     */
    public /*out*/ readonly secret!: pulumi.Output<string>;

    /**
     * Create a Key resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: KeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: KeyArgs | KeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as KeyState | undefined;
            resourceInputs["dsnCsp"] = state ? state.dsnCsp : undefined;
            resourceInputs["dsnPublic"] = state ? state.dsnPublic : undefined;
            resourceInputs["dsnSecret"] = state ? state.dsnSecret : undefined;
            resourceInputs["isActive"] = state ? state.isActive : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["organization"] = state ? state.organization : undefined;
            resourceInputs["project"] = state ? state.project : undefined;
            resourceInputs["projectId"] = state ? state.projectId : undefined;
            resourceInputs["public"] = state ? state.public : undefined;
            resourceInputs["rateLimitCount"] = state ? state.rateLimitCount : undefined;
            resourceInputs["rateLimitWindow"] = state ? state.rateLimitWindow : undefined;
            resourceInputs["secret"] = state ? state.secret : undefined;
        } else {
            const args = argsOrState as KeyArgs | undefined;
            if ((!args || args.organization === undefined) && !opts.urn) {
                throw new Error("Missing required property 'organization'");
            }
            if ((!args || args.project === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["organization"] = args ? args.organization : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["rateLimitCount"] = args ? args.rateLimitCount : undefined;
            resourceInputs["rateLimitWindow"] = args ? args.rateLimitWindow : undefined;
            resourceInputs["dsnCsp"] = undefined /*out*/;
            resourceInputs["dsnPublic"] = undefined /*out*/;
            resourceInputs["dsnSecret"] = undefined /*out*/;
            resourceInputs["isActive"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["public"] = undefined /*out*/;
            resourceInputs["secret"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Key.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Key resources.
 */
export interface KeyState {
    /**
     * DSN for the Content Security Policy (CSP) for the key.
     */
    dsnCsp?: pulumi.Input<string>;
    /**
     * DSN for the key.
     */
    dsnPublic?: pulumi.Input<string>;
    /**
     * @deprecated DSN (Deprecated) for the key.
     */
    dsnSecret?: pulumi.Input<string>;
    /**
     * Flag indicating the key is active.
     */
    isActive?: pulumi.Input<boolean>;
    /**
     * The name of the key.
     */
    name?: pulumi.Input<string>;
    /**
     * The slug of the organization the key should be created for.
     */
    organization?: pulumi.Input<string>;
    /**
     * The slug of the project the key should be created for.
     */
    project?: pulumi.Input<string>;
    /**
     * The ID of the project that the key belongs to.
     */
    projectId?: pulumi.Input<number>;
    /**
     * Public key portion of the client key.
     */
    public?: pulumi.Input<string>;
    /**
     * Number of events that can be reported within the rate limit window.
     */
    rateLimitCount?: pulumi.Input<number>;
    /**
     * Length of time that will be considered when checking the rate limit.
     */
    rateLimitWindow?: pulumi.Input<number>;
    /**
     * Secret key portion of the client key.
     */
    secret?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Key resource.
 */
export interface KeyArgs {
    /**
     * The name of the key.
     */
    name?: pulumi.Input<string>;
    /**
     * The slug of the organization the key should be created for.
     */
    organization: pulumi.Input<string>;
    /**
     * The slug of the project the key should be created for.
     */
    project: pulumi.Input<string>;
    /**
     * Number of events that can be reported within the rate limit window.
     */
    rateLimitCount?: pulumi.Input<number>;
    /**
     * Length of time that will be considered when checking the rate limit.
     */
    rateLimitWindow?: pulumi.Input<number>;
}
